spring:
  application:
    name: EasyUseClipboardBackend
  redis:
    database: 0
    host: 127.0.0.1
    port: 6380
    password:
    timeout: 3000
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/easyuse_clipboard_db
      username: root
      password: root
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  data:
    SECRET: irUXxBLnoEd-d-N$`p\h
    tokenHeader: Authorization
    expiration: 30
    tokenHead: Bearer